# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `authentication-zero` gem.
# Please instead update this file by running `bin/tapioca gem authentication-zero`.

# source://authentication-zero//lib/authentication_zero/version.rb#1
module AuthenticationZero; end

# source://authentication-zero//lib/authentication_zero/version.rb#2
AuthenticationZero::VERSION = T.let(T.unsafe(nil), String)
