version: '3.1'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: wishlist
      POSTGRES_DB: wishlist_development
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./tmp/minio:/data
    environment:
      - "MINIO_ACCESS_KEY=wishlist"
      - "MINIO_SECRET_KEY=wishlist123"
    command: server /data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 wishlist music123;
      /usr/bin/mc mb minio/wishlist-dev;
      /usr/bin/mc mb minio/wishlist-test;
      exit 0;
      "
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
