# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::ApplicationComponent`.
# Please instead update this file by running `bin/tapioca dsl Components::ApplicationComponent`.

class Components::ApplicationComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
