# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SessionMailer`.
# Please instead update this file by running `bin/tapioca dsl SessionMailer`.

class SessionMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def signed_in_notification; end
  end
end
