default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wishlist_development
  username: wishlist
  password: wishlist
  host: localhost
  port: 5432
    
test:
  <<: *default
  database: wishlist_test
  username: wishlist
  password: wishlist
  host: localhost
  port: 5432
    
production:
  <<: *default
  database: wishlist_production
  username: wishlist
  password: <%= ENV["DATABASE_PASSWORD"] %>
