test:
  service: S3
  access_key_id: wishlist
  secret_access_key: wishlist123
  region: us-east-1
  bucket: wishlist-test
  endpoint: "http://localhost:9000"
  force_path_style: true

local:
  service: S3
  access_key_id: wishlist
  secret_access_key: wishlist123
  region: us-east-1
  bucket: wishlist-dev
  endpoint: "http://localhost:9000"
  force_path_style: true

prod:
  service: S3
  access_key_id: <%= ENV["MINIO_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["MINIO_SECRET_ACCESS_KEY"] %>
  region: us-east-1
  bucket: wishlist
  endpoint: <%= ENV["MINIO_ENDPOINT"] %>
  force_path_style: true
