# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bootstrap::Component`.
# Please instead update this file by running `bin/tapioca dsl Bootstrap::Component`.

class Bootstrap::Component
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
